/*
 * This file is generated by jOOQ.
 */
package foatto.jooq.core.tables.references


import foatto.jooq.core.tables.SystemAlert
import foatto.jooq.core.tables.SystemAlias
import foatto.jooq.core.tables.SystemFileStore
import foatto.jooq.core.tables.SystemNew
import foatto.jooq.core.tables.SystemOtherOwner
import foatto.jooq.core.tables.SystemPermission
import foatto.jooq.core.tables.SystemReplicationReceive
import foatto.jooq.core.tables.SystemReplicationSend
import foatto.jooq.core.tables.SystemRole
import foatto.jooq.core.tables.SystemRolePermission
import foatto.jooq.core.tables.SystemUserProperty
import foatto.jooq.core.tables.SystemUserRole
import foatto.jooq.core.tables.SystemUsers



/**
 * The table <code>public.system_alert</code>.
 */
val SYSTEM_ALERT = SystemAlert.SYSTEM_ALERT

/**
 * The table <code>public.system_alias</code>.
 */
val SYSTEM_ALIAS = SystemAlias.SYSTEM_ALIAS

/**
 * The table <code>public.system_file_store</code>.
 */
val SYSTEM_FILE_STORE = SystemFileStore.SYSTEM_FILE_STORE

/**
 * The table <code>public.system_new</code>.
 */
val SYSTEM_NEW = SystemNew.SYSTEM_NEW

/**
 * The table <code>public.system_other_owner</code>.
 */
val SYSTEM_OTHER_OWNER = SystemOtherOwner.SYSTEM_OTHER_OWNER

/**
 * The table <code>public.system_permission</code>.
 */
val SYSTEM_PERMISSION = SystemPermission.SYSTEM_PERMISSION

/**
 * The table <code>public.system_replication_receive</code>.
 */
val SYSTEM_REPLICATION_RECEIVE = SystemReplicationReceive.SYSTEM_REPLICATION_RECEIVE

/**
 * The table <code>public.system_replication_send</code>.
 */
val SYSTEM_REPLICATION_SEND = SystemReplicationSend.SYSTEM_REPLICATION_SEND

/**
 * The table <code>public.system_role</code>.
 */
val SYSTEM_ROLE = SystemRole.SYSTEM_ROLE

/**
 * The table <code>public.system_role_permission</code>.
 */
val SYSTEM_ROLE_PERMISSION = SystemRolePermission.SYSTEM_ROLE_PERMISSION

/**
 * The table <code>public.system_user_property</code>.
 */
val SYSTEM_USER_PROPERTY = SystemUserProperty.SYSTEM_USER_PROPERTY

/**
 * The table <code>public.system_user_role</code>.
 */
val SYSTEM_USER_ROLE = SystemUserRole.SYSTEM_USER_ROLE

/**
 * The table <code>public.system_users</code>.
 */
val SYSTEM_USERS = SystemUsers.SYSTEM_USERS
