package foatto.mms.core_mms.sensor.config

class SensorConfigEnergoAnalogue(
    aId: Int,
    aName: String,
    aGroup: String,
    aDescr: String,
    aPortNum: Int,
    aSensorType: Int,
    aSmoothMethod: Int,
    aSmoothTime: Int,
    aMinIgnore: Double,
    aMaxIgnore: Double,
    val phase: Int,
    aMinView: Double,
    aMaxView: Double,
    aMinLimit: Double,
    aMaxLimit: Double,
) : SensorConfigAnalogue(
    aId = aId,
    aName = aName,
    aGroup = aGroup,
    aDescr = aDescr,
    aPortNum = aPortNum,
    aSensorType = aSensorType,
    aSmoothMethod = aSmoothMethod,
    aSmoothTime = aSmoothTime,
    aMinIgnore = aMinIgnore,
    aMaxIgnore = aMaxIgnore,
    minView = aMinView,
    maxView = aMaxView,
    minLimit = aMinLimit,
    maxLimit = aMaxLimit,
)
