package foatto.mms.core_mms.sensor.config

class SensorConfigWork(
    aId: Int,
    aName: String,
    aGroup: String,
    aDescr: String,
    aPortNum: Int,
    aSensorType: Int,
    aSerialNo: String,
    aBegYe: Int,
    aBegMo: Int,
    aBegDa: Int,
    val boundValue: Int,
    val activeValue: Int,
    val minOnTime: Int,
    val minOffTime: Int,
    val begWorkValue: Double,
    val cmdOnId: Int,
    val cmdOffId: Int,
    val signalOn: SignalConfig,
    val signalOff: SignalConfig,
    val minIgnore: Double,
    val maxIgnore: Double,
    val liquidName: String,
    val liquidNorm: Double
) : SensorConfig(
    id = aId,
    name = aName,
    group = aGroup,
    descr = aDescr,
    portNum = aPortNum,
    sensorType = aSensorType,
    serialNo = aSerialNo,
    begYe = aBegYe,
    begMo = aBegMo,
    begDa = aBegDa,
)