package foatto.mms.core_mms.ds

object GalileoFunction {

    val PORT_NUM_MERCURY_COUNT_ACTIVE_DIRECT = 160
    val PORT_NUM_MERCURY_COUNT_ACTIVE_REVERSE = 164
    val PORT_NUM_MERCURY_COUNT_REACTIVE_DIRECT = 168
    val PORT_NUM_MERCURY_COUNT_REACTIVE_REVERSE = 172
    val PORT_NUM_MERCURY_VOLTAGE_A = 180
    val PORT_NUM_MERCURY_VOLTAGE_B = 184
    val PORT_NUM_MERCURY_VOLTAGE_C = 188
    val PORT_NUM_MERCURY_CURRENT_A = 200
    val PORT_NUM_MERCURY_CURRENT_B = 204
    val PORT_NUM_MERCURY_CURRENT_C = 208
    val PORT_NUM_MERCURY_POWER_KOEF_A = 220
    val PORT_NUM_MERCURY_POWER_KOEF_B = 224
    val PORT_NUM_MERCURY_POWER_KOEF_C = 228
    val PORT_NUM_MERCURY_POWER_ACTIVE_A = 232
    val PORT_NUM_MERCURY_POWER_ACTIVE_B = 236
    val PORT_NUM_MERCURY_POWER_ACTIVE_C = 240
    val PORT_NUM_MERCURY_POWER_REACTIVE_A = 244
    val PORT_NUM_MERCURY_POWER_REACTIVE_B = 248
    val PORT_NUM_MERCURY_POWER_REACTIVE_C = 252
    val PORT_NUM_MERCURY_POWER_FULL_A = 256
    val PORT_NUM_MERCURY_POWER_FULL_B = 260
    val PORT_NUM_MERCURY_POWER_FULL_C = 264

    val PORT_NUM_EMIS_MASS_FLOW = 270
    val PORT_NUM_EMIS_DENSITY = 280
    val PORT_NUM_EMIS_TEMPERATURE = 290
    val PORT_NUM_EMIS_VOLUME_FLOW = 300
    val PORT_NUM_EMIS_ACCUMULATED_MASS = 310
    val PORT_NUM_EMIS_ACCUMULATED_VOLUME = 320

    val PORT_NUM_MERCURY_POWER_ACTIVE_ABC = 330
    val PORT_NUM_MERCURY_POWER_REACTIVE_ABC = 340
    val PORT_NUM_MERCURY_POWER_FULL_ABC = 350

    val PORT_NUM_USS_ACCUMULATED_VOLUME = 360

    val PORT_NUM_ESD_STATUS = 500
    val PORT_NUM_ESD_VOLUME = 504
    val PORT_NUM_ESD_FLOW = 508
    val PORT_NUM_ESD_CAMERA_VOLUME = 512
    val PORT_NUM_ESD_CAMERA_FLOW = 516
    val PORT_NUM_ESD_CAMERA_TEMPERATURE = 520
    val PORT_NUM_ESD_REVERSE_CAMERA_VOLUME = 524
    val PORT_NUM_ESD_REVERSE_CAMERA_FLOW = 528
    val PORT_NUM_ESD_REVERSE_CAMERA_TEMPERATURE = 532
}