/*
 * This file is generated by jOOQ.
 */
package foatto.jooq.core.tables


import foatto.jooq.core.Public
import foatto.jooq.core.indexes.SYSTEM_FILE_STORE_FILE_ID
import foatto.jooq.core.indexes.SYSTEM_FILE_STORE_ID
import foatto.jooq.core.tables.records.SystemFileStoreRecord

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row5
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SystemFileStore(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, SystemFileStoreRecord>?,
    aliased: Table<SystemFileStoreRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<SystemFileStoreRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.system_file_store</code>
         */
        val SYSTEM_FILE_STORE = SystemFileStore()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<SystemFileStoreRecord> = SystemFileStoreRecord::class.java

    /**
     * The column <code>public.system_file_store.id</code>.
     */
    val ID: TableField<SystemFileStoreRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.system_file_store.file_id</code>.
     */
    val FILE_ID: TableField<SystemFileStoreRecord, Int?> = createField(DSL.name("file_id"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.system_file_store.name</code>.
     */
    val NAME: TableField<SystemFileStoreRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(250), this, "")

    /**
     * The column <code>public.system_file_store.dir</code>.
     */
    val DIR: TableField<SystemFileStoreRecord, String?> = createField(DSL.name("dir"), SQLDataType.VARCHAR(250), this, "")

    /**
     * The column <code>public.system_file_store.comment</code>.
     */
    val COMMENT: TableField<SystemFileStoreRecord, String?> = createField(DSL.name("comment"), SQLDataType.VARCHAR(250), this, "")

    private constructor(alias: Name, aliased: Table<SystemFileStoreRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<SystemFileStoreRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.system_file_store</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.system_file_store</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.system_file_store</code> table reference
     */
    constructor(): this(DSL.name("system_file_store"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, SystemFileStoreRecord>): this(Internal.createPathAlias(child, key), child, key, SYSTEM_FILE_STORE, null)
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(SYSTEM_FILE_STORE_FILE_ID, SYSTEM_FILE_STORE_ID)
    override fun `as`(alias: String): SystemFileStore = SystemFileStore(DSL.name(alias), this)
    override fun `as`(alias: Name): SystemFileStore = SystemFileStore(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): SystemFileStore = SystemFileStore(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): SystemFileStore = SystemFileStore(name, null)

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row5<Int?, Int?, String?, String?, String?> = super.fieldsRow() as Row5<Int?, Int?, String?, String?, String?>
}
