/*
 * This file is generated by jOOQ.
 */
package foatto.jooq.core.tables


import foatto.jooq.core.Public
import foatto.jooq.core.indexes.SYSTEM_ALERT_ROW
import foatto.jooq.core.indexes.SYSTEM_ALERT_TIME
import foatto.jooq.core.keys.SYSTEM_ALERT_PKEY
import foatto.jooq.core.tables.records.SystemAlertRecord

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row4
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SystemAlert(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, SystemAlertRecord>?,
    aliased: Table<SystemAlertRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<SystemAlertRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.system_alert</code>
         */
        val SYSTEM_ALERT = SystemAlert()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<SystemAlertRecord> = SystemAlertRecord::class.java

    /**
     * The column <code>public.system_alert.id</code>.
     */
    val ID: TableField<SystemAlertRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.system_alert.alert_time</code>.
     */
    val ALERT_TIME: TableField<SystemAlertRecord, Int?> = createField(DSL.name("alert_time"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.system_alert.tag</code>.
     */
    val TAG: TableField<SystemAlertRecord, String?> = createField(DSL.name("tag"), SQLDataType.VARCHAR(250), this, "")

    /**
     * The column <code>public.system_alert.row_id</code>.
     */
    val ROW_ID: TableField<SystemAlertRecord, Int?> = createField(DSL.name("row_id"), SQLDataType.INTEGER, this, "")

    private constructor(alias: Name, aliased: Table<SystemAlertRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<SystemAlertRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.system_alert</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.system_alert</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.system_alert</code> table reference
     */
    constructor(): this(DSL.name("system_alert"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, SystemAlertRecord>): this(Internal.createPathAlias(child, key), child, key, SYSTEM_ALERT, null)
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(SYSTEM_ALERT_ROW, SYSTEM_ALERT_TIME)
    override fun getPrimaryKey(): UniqueKey<SystemAlertRecord> = SYSTEM_ALERT_PKEY
    override fun getKeys(): List<UniqueKey<SystemAlertRecord>> = listOf(SYSTEM_ALERT_PKEY)
    override fun `as`(alias: String): SystemAlert = SystemAlert(DSL.name(alias), this)
    override fun `as`(alias: Name): SystemAlert = SystemAlert(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): SystemAlert = SystemAlert(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): SystemAlert = SystemAlert(name, null)

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row4<Int?, Int?, String?, Int?> = super.fieldsRow() as Row4<Int?, Int?, String?, Int?>
}
