/*
 * This file is generated by jOOQ.
 */
package foatto.jooq.core.tables


import foatto.jooq.core.Public
import foatto.jooq.core.indexes.SYSTEM_ROLE_NAME
import foatto.jooq.core.keys.SYSTEM_ROLE_PKEY
import foatto.jooq.core.tables.records.SystemRoleRecord

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row2
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SystemRole(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, SystemRoleRecord>?,
    aliased: Table<SystemRoleRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<SystemRoleRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.system_role</code>
         */
        val SYSTEM_ROLE = SystemRole()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<SystemRoleRecord> = SystemRoleRecord::class.java

    /**
     * The column <code>public.system_role.id</code>.
     */
    val ID: TableField<SystemRoleRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.system_role.name</code>.
     */
    val NAME: TableField<SystemRoleRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(250), this, "")

    private constructor(alias: Name, aliased: Table<SystemRoleRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<SystemRoleRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.system_role</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.system_role</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.system_role</code> table reference
     */
    constructor(): this(DSL.name("system_role"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, SystemRoleRecord>): this(Internal.createPathAlias(child, key), child, key, SYSTEM_ROLE, null)
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(SYSTEM_ROLE_NAME)
    override fun getPrimaryKey(): UniqueKey<SystemRoleRecord> = SYSTEM_ROLE_PKEY
    override fun getKeys(): List<UniqueKey<SystemRoleRecord>> = listOf(SYSTEM_ROLE_PKEY)
    override fun `as`(alias: String): SystemRole = SystemRole(DSL.name(alias), this)
    override fun `as`(alias: Name): SystemRole = SystemRole(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): SystemRole = SystemRole(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): SystemRole = SystemRole(name, null)

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row2<Int?, String?> = super.fieldsRow() as Row2<Int?, String?>
}
