/*
 * This file is generated by jOOQ.
 */
package foatto.jooq.core.tables


import foatto.jooq.core.Public
import foatto.jooq.core.indexes.SYSTEM_ROLE_PERMISSION_P_ID
import foatto.jooq.core.indexes.SYSTEM_ROLE_PERMISSION_P_VALUE
import foatto.jooq.core.indexes.SYSTEM_ROLE_PERMISSION_ROLE
import foatto.jooq.core.keys.SYSTEM_ROLE_PERMISSION_PKEY
import foatto.jooq.core.tables.records.SystemRolePermissionRecord

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row4
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SystemRolePermission(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, SystemRolePermissionRecord>?,
    aliased: Table<SystemRolePermissionRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<SystemRolePermissionRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.system_role_permission</code>
         */
        val SYSTEM_ROLE_PERMISSION = SystemRolePermission()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<SystemRolePermissionRecord> = SystemRolePermissionRecord::class.java

    /**
     * The column <code>public.system_role_permission.id</code>.
     */
    val ID: TableField<SystemRolePermissionRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.system_role_permission.role_id</code>.
     */
    val ROLE_ID: TableField<SystemRolePermissionRecord, Int?> = createField(DSL.name("role_id"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.system_role_permission.permission_id</code>.
     */
    val PERMISSION_ID: TableField<SystemRolePermissionRecord, Int?> = createField(DSL.name("permission_id"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.system_role_permission.permission_value</code>.
     */
    val PERMISSION_VALUE: TableField<SystemRolePermissionRecord, Int?> = createField(DSL.name("permission_value"), SQLDataType.INTEGER, this, "")

    private constructor(alias: Name, aliased: Table<SystemRolePermissionRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<SystemRolePermissionRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.system_role_permission</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.system_role_permission</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.system_role_permission</code> table reference
     */
    constructor(): this(DSL.name("system_role_permission"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, SystemRolePermissionRecord>): this(Internal.createPathAlias(child, key), child, key, SYSTEM_ROLE_PERMISSION, null)
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(SYSTEM_ROLE_PERMISSION_P_ID, SYSTEM_ROLE_PERMISSION_P_VALUE, SYSTEM_ROLE_PERMISSION_ROLE)
    override fun getPrimaryKey(): UniqueKey<SystemRolePermissionRecord> = SYSTEM_ROLE_PERMISSION_PKEY
    override fun getKeys(): List<UniqueKey<SystemRolePermissionRecord>> = listOf(SYSTEM_ROLE_PERMISSION_PKEY)
    override fun `as`(alias: String): SystemRolePermission = SystemRolePermission(DSL.name(alias), this)
    override fun `as`(alias: Name): SystemRolePermission = SystemRolePermission(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): SystemRolePermission = SystemRolePermission(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): SystemRolePermission = SystemRolePermission(name, null)

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row4<Int?, Int?, Int?, Int?> = super.fieldsRow() as Row4<Int?, Int?, Int?, Int?>
}
