/*
 * This file is generated by jOOQ.
 */
package foatto.jooq.core.tables


import foatto.jooq.core.Public
import foatto.jooq.core.indexes.SYSTEM_OTHER_OWNER_ALIAS
import foatto.jooq.core.indexes.SYSTEM_OTHER_OWNER_ROW
import foatto.jooq.core.indexes.SYSTEM_OTHER_OWNER_USER
import foatto.jooq.core.keys.SYSTEM_OTHER_OWNER_PKEY
import foatto.jooq.core.tables.records.SystemOtherOwnerRecord

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row4
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SystemOtherOwner(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, SystemOtherOwnerRecord>?,
    aliased: Table<SystemOtherOwnerRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<SystemOtherOwnerRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.system_other_owner</code>
         */
        val SYSTEM_OTHER_OWNER = SystemOtherOwner()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<SystemOtherOwnerRecord> = SystemOtherOwnerRecord::class.java

    /**
     * The column <code>public.system_other_owner.id</code>.
     */
    val ID: TableField<SystemOtherOwnerRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.system_other_owner.alias_id</code>.
     */
    val ALIAS_ID: TableField<SystemOtherOwnerRecord, Int?> = createField(DSL.name("alias_id"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.system_other_owner.row_id</code>.
     */
    val ROW_ID: TableField<SystemOtherOwnerRecord, Int?> = createField(DSL.name("row_id"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.system_other_owner.user_id</code>.
     */
    val USER_ID: TableField<SystemOtherOwnerRecord, Int?> = createField(DSL.name("user_id"), SQLDataType.INTEGER, this, "")

    private constructor(alias: Name, aliased: Table<SystemOtherOwnerRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<SystemOtherOwnerRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.system_other_owner</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.system_other_owner</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.system_other_owner</code> table reference
     */
    constructor(): this(DSL.name("system_other_owner"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, SystemOtherOwnerRecord>): this(Internal.createPathAlias(child, key), child, key, SYSTEM_OTHER_OWNER, null)
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(SYSTEM_OTHER_OWNER_ALIAS, SYSTEM_OTHER_OWNER_ROW, SYSTEM_OTHER_OWNER_USER)
    override fun getPrimaryKey(): UniqueKey<SystemOtherOwnerRecord> = SYSTEM_OTHER_OWNER_PKEY
    override fun getKeys(): List<UniqueKey<SystemOtherOwnerRecord>> = listOf(SYSTEM_OTHER_OWNER_PKEY)
    override fun `as`(alias: String): SystemOtherOwner = SystemOtherOwner(DSL.name(alias), this)
    override fun `as`(alias: Name): SystemOtherOwner = SystemOtherOwner(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): SystemOtherOwner = SystemOtherOwner(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): SystemOtherOwner = SystemOtherOwner(name, null)

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row4<Int?, Int?, Int?, Int?> = super.fieldsRow() as Row4<Int?, Int?, Int?, Int?>
}
