/*
 * This file is generated by jOOQ.
 */
package foatto.jooq.core.tables.records


import foatto.jooq.core.tables.SystemAlias

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record12
import org.jooq.Row12
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SystemAliasRecord() : UpdatableRecordImpl<SystemAliasRecord>(SystemAlias.SYSTEM_ALIAS), Record12<Int?, String?, String?, String?, String?, Int?, Int?, Int?, Int?, Int?, Int?, Int?> {

    var id: Int?
        set(value) = set(0, value)
        get() = get(0) as Int?

    var name: String?
        set(value) = set(1, value)
        get() = get(1) as String?

    var controlName: String?
        set(value) = set(2, value)
        get() = get(2) as String?

    var modelName: String?
        set(value) = set(3, value)
        get() = get(3) as String?

    var descr: String?
        set(value) = set(4, value)
        get() = get(4) as String?

    var authorizationNeed: Int?
        set(value) = set(5, value)
        get() = get(5) as Int?

    var showRowNo: Int?
        set(value) = set(6, value)
        get() = get(6) as Int?

    var showUserColumn: Int?
        set(value) = set(7, value)
        get() = get(7) as Int?

    var tablePageSize: Int?
        set(value) = set(8, value)
        get() = get(8) as Int?

    var newable: Int?
        set(value) = set(9, value)
        get() = get(9) as Int?

    var newAutoRead: Int?
        set(value) = set(10, value)
        get() = get(10) as Int?

    var defaultParentUser: Int?
        set(value) = set(11, value)
        get() = get(11) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row12<Int?, String?, String?, String?, String?, Int?, Int?, Int?, Int?, Int?, Int?, Int?> = super.fieldsRow() as Row12<Int?, String?, String?, String?, String?, Int?, Int?, Int?, Int?, Int?, Int?, Int?>
    override fun valuesRow(): Row12<Int?, String?, String?, String?, String?, Int?, Int?, Int?, Int?, Int?, Int?, Int?> = super.valuesRow() as Row12<Int?, String?, String?, String?, String?, Int?, Int?, Int?, Int?, Int?, Int?, Int?>
    override fun field1(): Field<Int?> = SystemAlias.SYSTEM_ALIAS.ID
    override fun field2(): Field<String?> = SystemAlias.SYSTEM_ALIAS.NAME
    override fun field3(): Field<String?> = SystemAlias.SYSTEM_ALIAS.CONTROL_NAME
    override fun field4(): Field<String?> = SystemAlias.SYSTEM_ALIAS.MODEL_NAME
    override fun field5(): Field<String?> = SystemAlias.SYSTEM_ALIAS.DESCR
    override fun field6(): Field<Int?> = SystemAlias.SYSTEM_ALIAS.AUTHORIZATION_NEED
    override fun field7(): Field<Int?> = SystemAlias.SYSTEM_ALIAS.SHOW_ROW_NO
    override fun field8(): Field<Int?> = SystemAlias.SYSTEM_ALIAS.SHOW_USER_COLUMN
    override fun field9(): Field<Int?> = SystemAlias.SYSTEM_ALIAS.TABLE_PAGE_SIZE
    override fun field10(): Field<Int?> = SystemAlias.SYSTEM_ALIAS.NEWABLE
    override fun field11(): Field<Int?> = SystemAlias.SYSTEM_ALIAS.NEW_AUTO_READ
    override fun field12(): Field<Int?> = SystemAlias.SYSTEM_ALIAS.DEFAULT_PARENT_USER
    override fun component1(): Int? = id
    override fun component2(): String? = name
    override fun component3(): String? = controlName
    override fun component4(): String? = modelName
    override fun component5(): String? = descr
    override fun component6(): Int? = authorizationNeed
    override fun component7(): Int? = showRowNo
    override fun component8(): Int? = showUserColumn
    override fun component9(): Int? = tablePageSize
    override fun component10(): Int? = newable
    override fun component11(): Int? = newAutoRead
    override fun component12(): Int? = defaultParentUser
    override fun value1(): Int? = id
    override fun value2(): String? = name
    override fun value3(): String? = controlName
    override fun value4(): String? = modelName
    override fun value5(): String? = descr
    override fun value6(): Int? = authorizationNeed
    override fun value7(): Int? = showRowNo
    override fun value8(): Int? = showUserColumn
    override fun value9(): Int? = tablePageSize
    override fun value10(): Int? = newable
    override fun value11(): Int? = newAutoRead
    override fun value12(): Int? = defaultParentUser

    override fun value1(value: Int?): SystemAliasRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): SystemAliasRecord {
        this.name = value
        return this
    }

    override fun value3(value: String?): SystemAliasRecord {
        this.controlName = value
        return this
    }

    override fun value4(value: String?): SystemAliasRecord {
        this.modelName = value
        return this
    }

    override fun value5(value: String?): SystemAliasRecord {
        this.descr = value
        return this
    }

    override fun value6(value: Int?): SystemAliasRecord {
        this.authorizationNeed = value
        return this
    }

    override fun value7(value: Int?): SystemAliasRecord {
        this.showRowNo = value
        return this
    }

    override fun value8(value: Int?): SystemAliasRecord {
        this.showUserColumn = value
        return this
    }

    override fun value9(value: Int?): SystemAliasRecord {
        this.tablePageSize = value
        return this
    }

    override fun value10(value: Int?): SystemAliasRecord {
        this.newable = value
        return this
    }

    override fun value11(value: Int?): SystemAliasRecord {
        this.newAutoRead = value
        return this
    }

    override fun value12(value: Int?): SystemAliasRecord {
        this.defaultParentUser = value
        return this
    }

    override fun values(value1: Int?, value2: String?, value3: String?, value4: String?, value5: String?, value6: Int?, value7: Int?, value8: Int?, value9: Int?, value10: Int?, value11: Int?, value12: Int?): SystemAliasRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        this.value12(value12)
        return this
    }

    /**
     * Create a detached, initialised SystemAliasRecord
     */
    constructor(id: Int? = null, name: String? = null, controlName: String? = null, modelName: String? = null, descr: String? = null, authorizationNeed: Int? = null, showRowNo: Int? = null, showUserColumn: Int? = null, tablePageSize: Int? = null, newable: Int? = null, newAutoRead: Int? = null, defaultParentUser: Int? = null): this() {
        this.id = id
        this.name = name
        this.controlName = controlName
        this.modelName = modelName
        this.descr = descr
        this.authorizationNeed = authorizationNeed
        this.showRowNo = showRowNo
        this.showUserColumn = showUserColumn
        this.tablePageSize = tablePageSize
        this.newable = newable
        this.newAutoRead = newAutoRead
        this.defaultParentUser = defaultParentUser
    }
}
