/*
 * This file is generated by jOOQ.
 */
package foatto.jooq.core.tables.records


import foatto.jooq.core.tables.SystemOtherOwner

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record4
import org.jooq.Row4
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SystemOtherOwnerRecord() : UpdatableRecordImpl<SystemOtherOwnerRecord>(SystemOtherOwner.SYSTEM_OTHER_OWNER), Record4<Int?, Int?, Int?, Int?> {

    var id: Int?
        set(value) = set(0, value)
        get() = get(0) as Int?

    var aliasId: Int?
        set(value) = set(1, value)
        get() = get(1) as Int?

    var rowId: Int?
        set(value) = set(2, value)
        get() = get(2) as Int?

    var userId: Int?
        set(value) = set(3, value)
        get() = get(3) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row4<Int?, Int?, Int?, Int?> = super.fieldsRow() as Row4<Int?, Int?, Int?, Int?>
    override fun valuesRow(): Row4<Int?, Int?, Int?, Int?> = super.valuesRow() as Row4<Int?, Int?, Int?, Int?>
    override fun field1(): Field<Int?> = SystemOtherOwner.SYSTEM_OTHER_OWNER.ID
    override fun field2(): Field<Int?> = SystemOtherOwner.SYSTEM_OTHER_OWNER.ALIAS_ID
    override fun field3(): Field<Int?> = SystemOtherOwner.SYSTEM_OTHER_OWNER.ROW_ID
    override fun field4(): Field<Int?> = SystemOtherOwner.SYSTEM_OTHER_OWNER.USER_ID
    override fun component1(): Int? = id
    override fun component2(): Int? = aliasId
    override fun component3(): Int? = rowId
    override fun component4(): Int? = userId
    override fun value1(): Int? = id
    override fun value2(): Int? = aliasId
    override fun value3(): Int? = rowId
    override fun value4(): Int? = userId

    override fun value1(value: Int?): SystemOtherOwnerRecord {
        this.id = value
        return this
    }

    override fun value2(value: Int?): SystemOtherOwnerRecord {
        this.aliasId = value
        return this
    }

    override fun value3(value: Int?): SystemOtherOwnerRecord {
        this.rowId = value
        return this
    }

    override fun value4(value: Int?): SystemOtherOwnerRecord {
        this.userId = value
        return this
    }

    override fun values(value1: Int?, value2: Int?, value3: Int?, value4: Int?): SystemOtherOwnerRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        return this
    }

    /**
     * Create a detached, initialised SystemOtherOwnerRecord
     */
    constructor(id: Int? = null, aliasId: Int? = null, rowId: Int? = null, userId: Int? = null): this() {
        this.id = id
        this.aliasId = aliasId
        this.rowId = rowId
        this.userId = userId
    }
}
