/*
 * This file is generated by jOOQ.
 */
package foatto.jooq.core.tables.records


import foatto.jooq.core.tables.SystemRole

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record2
import org.jooq.Row2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SystemRoleRecord() : UpdatableRecordImpl<SystemRoleRecord>(SystemRole.SYSTEM_ROLE), Record2<Int?, String?> {

    var id: Int?
        set(value) = set(0, value)
        get() = get(0) as Int?

    var name: String?
        set(value) = set(1, value)
        get() = get(1) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row2<Int?, String?> = super.fieldsRow() as Row2<Int?, String?>
    override fun valuesRow(): Row2<Int?, String?> = super.valuesRow() as Row2<Int?, String?>
    override fun field1(): Field<Int?> = SystemRole.SYSTEM_ROLE.ID
    override fun field2(): Field<String?> = SystemRole.SYSTEM_ROLE.NAME
    override fun component1(): Int? = id
    override fun component2(): String? = name
    override fun value1(): Int? = id
    override fun value2(): String? = name

    override fun value1(value: Int?): SystemRoleRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): SystemRoleRecord {
        this.name = value
        return this
    }

    override fun values(value1: Int?, value2: String?): SystemRoleRecord {
        this.value1(value1)
        this.value2(value2)
        return this
    }

    /**
     * Create a detached, initialised SystemRoleRecord
     */
    constructor(id: Int? = null, name: String? = null): this() {
        this.id = id
        this.name = name
    }
}
