/*
 * This file is generated by jOOQ.
 */
package foatto.jooq.core.indexes


import foatto.jooq.core.tables.SystemAlert
import foatto.jooq.core.tables.SystemAlias
import foatto.jooq.core.tables.SystemFileStore
import foatto.jooq.core.tables.SystemNew
import foatto.jooq.core.tables.SystemOtherOwner
import foatto.jooq.core.tables.SystemPermission
import foatto.jooq.core.tables.SystemReplicationReceive
import foatto.jooq.core.tables.SystemReplicationSend
import foatto.jooq.core.tables.SystemRole
import foatto.jooq.core.tables.SystemRolePermission
import foatto.jooq.core.tables.SystemUserProperty
import foatto.jooq.core.tables.SystemUserRole
import foatto.jooq.core.tables.SystemUsers

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val SYSTEM_ALERT_ROW: Index = Internal.createIndex(DSL.name("system_alert_row"), SystemAlert.SYSTEM_ALERT, arrayOf(SystemAlert.SYSTEM_ALERT.ROW_ID), false)
val SYSTEM_ALERT_TIME: Index = Internal.createIndex(DSL.name("system_alert_time"), SystemAlert.SYSTEM_ALERT, arrayOf(SystemAlert.SYSTEM_ALERT.ALERT_TIME), false)
val SYSTEM_ALIAS_NAME: Index = Internal.createIndex(DSL.name("system_alias_name"), SystemAlias.SYSTEM_ALIAS, arrayOf(SystemAlias.SYSTEM_ALIAS.NAME), false)
val SYSTEM_FILE_STORE_FILE_ID: Index = Internal.createIndex(DSL.name("system_file_store_file_id"), SystemFileStore.SYSTEM_FILE_STORE, arrayOf(SystemFileStore.SYSTEM_FILE_STORE.FILE_ID), false)
val SYSTEM_FILE_STORE_ID: Index = Internal.createIndex(DSL.name("system_file_store_id"), SystemFileStore.SYSTEM_FILE_STORE, arrayOf(SystemFileStore.SYSTEM_FILE_STORE.ID), false)
val SYSTEM_NEW_ROW: Index = Internal.createIndex(DSL.name("system_new_row"), SystemNew.SYSTEM_NEW, arrayOf(SystemNew.SYSTEM_NEW.ROW_ID), false)
val SYSTEM_NEW_TABLE: Index = Internal.createIndex(DSL.name("system_new_table"), SystemNew.SYSTEM_NEW, arrayOf(SystemNew.SYSTEM_NEW.TABLE_NAME), false)
val SYSTEM_NEW_USER: Index = Internal.createIndex(DSL.name("system_new_user"), SystemNew.SYSTEM_NEW, arrayOf(SystemNew.SYSTEM_NEW.USER_ID), false)
val SYSTEM_OTHER_OWNER_ALIAS: Index = Internal.createIndex(DSL.name("system_other_owner_alias"), SystemOtherOwner.SYSTEM_OTHER_OWNER, arrayOf(SystemOtherOwner.SYSTEM_OTHER_OWNER.ALIAS_ID), false)
val SYSTEM_OTHER_OWNER_ROW: Index = Internal.createIndex(DSL.name("system_other_owner_row"), SystemOtherOwner.SYSTEM_OTHER_OWNER, arrayOf(SystemOtherOwner.SYSTEM_OTHER_OWNER.ROW_ID), false)
val SYSTEM_OTHER_OWNER_USER: Index = Internal.createIndex(DSL.name("system_other_owner_user"), SystemOtherOwner.SYSTEM_OTHER_OWNER, arrayOf(SystemOtherOwner.SYSTEM_OTHER_OWNER.USER_ID), false)
val SYSTEM_PERMISSION_CLASS: Index = Internal.createIndex(DSL.name("system_permission_class"), SystemPermission.SYSTEM_PERMISSION, arrayOf(SystemPermission.SYSTEM_PERMISSION.CLASS_ID), false)
val SYSTEM_REPLICATION_RECEIVE_DEST: Index = Internal.createIndex(DSL.name("system_replication_receive_dest"), SystemReplicationReceive.SYSTEM_REPLICATION_RECEIVE, arrayOf(SystemReplicationReceive.SYSTEM_REPLICATION_RECEIVE.DEST_NAME), false)
val SYSTEM_REPLICATION_RECEIVE_TIME_KEY: Index = Internal.createIndex(DSL.name("system_replication_receive_time_key"), SystemReplicationReceive.SYSTEM_REPLICATION_RECEIVE, arrayOf(SystemReplicationReceive.SYSTEM_REPLICATION_RECEIVE.TIME_KEY), false)
val SYSTEM_REPLICATION_SEND_DEST: Index = Internal.createIndex(DSL.name("system_replication_send_dest"), SystemReplicationSend.SYSTEM_REPLICATION_SEND, arrayOf(SystemReplicationSend.SYSTEM_REPLICATION_SEND.DEST_NAME), false)
val SYSTEM_REPLICATION_SEND_SOUR: Index = Internal.createIndex(DSL.name("system_replication_send_sour"), SystemReplicationSend.SYSTEM_REPLICATION_SEND, arrayOf(SystemReplicationSend.SYSTEM_REPLICATION_SEND.SOUR_NAME), false)
val SYSTEM_REPLICATION_SEND_TIME_KEY: Index = Internal.createIndex(DSL.name("system_replication_send_time_key"), SystemReplicationSend.SYSTEM_REPLICATION_SEND, arrayOf(SystemReplicationSend.SYSTEM_REPLICATION_SEND.TIME_KEY), false)
val SYSTEM_ROLE_NAME: Index = Internal.createIndex(DSL.name("system_role_name"), SystemRole.SYSTEM_ROLE, arrayOf(SystemRole.SYSTEM_ROLE.NAME), false)
val SYSTEM_ROLE_PERMISSION_P_ID: Index = Internal.createIndex(DSL.name("system_role_permission_p_id"), SystemRolePermission.SYSTEM_ROLE_PERMISSION, arrayOf(SystemRolePermission.SYSTEM_ROLE_PERMISSION.PERMISSION_ID), false)
val SYSTEM_ROLE_PERMISSION_P_VALUE: Index = Internal.createIndex(DSL.name("system_role_permission_p_value"), SystemRolePermission.SYSTEM_ROLE_PERMISSION, arrayOf(SystemRolePermission.SYSTEM_ROLE_PERMISSION.PERMISSION_VALUE), false)
val SYSTEM_ROLE_PERMISSION_ROLE: Index = Internal.createIndex(DSL.name("system_role_permission_role"), SystemRolePermission.SYSTEM_ROLE_PERMISSION, arrayOf(SystemRolePermission.SYSTEM_ROLE_PERMISSION.ROLE_ID), false)
val SYSTEM_USER_PROPERTY_NAME: Index = Internal.createIndex(DSL.name("system_user_property_name"), SystemUserProperty.SYSTEM_USER_PROPERTY, arrayOf(SystemUserProperty.SYSTEM_USER_PROPERTY.PROPERTY_NAME), false)
val SYSTEM_USER_PROPERTY_USER: Index = Internal.createIndex(DSL.name("system_user_property_user"), SystemUserProperty.SYSTEM_USER_PROPERTY, arrayOf(SystemUserProperty.SYSTEM_USER_PROPERTY.USER_ID), false)
val SYSTEM_USER_ROLE_ROLE: Index = Internal.createIndex(DSL.name("system_user_role_role"), SystemUserRole.SYSTEM_USER_ROLE, arrayOf(SystemUserRole.SYSTEM_USER_ROLE.ROLE_ID), false)
val SYSTEM_USER_ROLE_USER: Index = Internal.createIndex(DSL.name("system_user_role_user"), SystemUserRole.SYSTEM_USER_ROLE, arrayOf(SystemUserRole.SYSTEM_USER_ROLE.USER_ID), false)
val SYSTEM_USERS_DISABLED: Index = Internal.createIndex(DSL.name("system_users_disabled"), SystemUsers.SYSTEM_USERS, arrayOf(SystemUsers.SYSTEM_USERS.IS_DISABLED), false)
val SYSTEM_USERS_LOGIN: Index = Internal.createIndex(DSL.name("system_users_login"), SystemUsers.SYSTEM_USERS, arrayOf(SystemUsers.SYSTEM_USERS.LOGIN), false)
val SYSTEM_USERS_ORG_TYPE: Index = Internal.createIndex(DSL.name("system_users_org_type"), SystemUsers.SYSTEM_USERS, arrayOf(SystemUsers.SYSTEM_USERS.ORG_TYPE), false)
val SYSTEM_USERS_PARENT: Index = Internal.createIndex(DSL.name("system_users_parent"), SystemUsers.SYSTEM_USERS, arrayOf(SystemUsers.SYSTEM_USERS.PARENT_ID), false)
val SYSTEM_USERS_PWD: Index = Internal.createIndex(DSL.name("system_users_pwd"), SystemUsers.SYSTEM_USERS, arrayOf(SystemUsers.SYSTEM_USERS.PWD), false)
val SYSTEM_USERS_USER: Index = Internal.createIndex(DSL.name("system_users_user"), SystemUsers.SYSTEM_USERS, arrayOf(SystemUsers.SYSTEM_USERS.USER_ID), false)
